###
GET http://localhost:3000/practica/user

###
POST http://localhost:3000/practica/user/register
Content-Type: application/json

{
    "name": "Probando",
    "age": 20,
    "email": "jopeetass@gmail.com",
    "password": "12345678"
}

###
POST http://localhost:3000/practica/user/register/validation
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2ODEzODUxYmQ3ZDZlYjZmNzNiNzQzZmMiLCJyb2xlIjpbInVzZXIiXSwiaWF0IjoxNzQ2MTA5NzIzLCJleHAiOjE3NDYxMTY5MjN9.6i40t67bFNMWkCpFvj7PyZRGRhFgcL9Dk57lBup4mDU
Content-Type: application/json

{
    "code": "19e20c"
}


###
POST http://localhost:3000/practica/user/login
Content-Type: application/json

{
    "email": "jopeetass@gmail.com",
    "password": "12345678"
}


###
POST http://localhost:3000/practica/user/login
Content-Type: application/json

{
    "email": "hola@gmail.com",
    "password": "HolaMundo.01"
}


###
PUT http://localhost:3000/practica/user/personalData
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2U0MTIzMDViNmJlYWE3OTZhMDEzZWQiLCJyb2xlIjpbInVzZXIiXSwiaWF0IjoxNzQzMDAwNDYyLCJleHAiOjE3NDMwMDc2NjJ9.BCkGKXJTrxeE_ap_w8QHSqM9XrLawGYE6AVYTkqp9Hc
Content-Type: application/json

{
    "name2": "Diego22",
    "fullname": "Her",
    "nif": "12341234B"
}


###
PUT http://localhost:3000/practica/user/company
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2RjMjk5MTI2MTRlZWVjYjJkZWFmMTAiLCJyb2xlIjpbInVzZXIiXSwiaWF0IjoxNzQyOTk3MTc3LCJleHAiOjE3NDMwMDQzNzd9._c0BaPtkkdBVkVOf1xOz8ImJHZlciwHVdCro7gRiskw
Content-Type: application/json

{
    "name": "U-Tad",
    "cif": "12349078B",
    "address": "Rozas"
}


###
PATCH http://localhost:3000/practica/user/logo
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2U0MTIzMDViNmJlYWE3OTZhMDEzZWQiLCJyb2xlIjpbInVzZXIiXSwiaWF0IjoxNzQzMDcwNzUxLCJleHAiOjE3NDMwNzc5NTF9.wYIKyJx0q9qbDvWmhVGzfPGuBusRRPCysDW18mOajIw
Content-Type: multipart/form-data; boundary=boundary123

--boundary123
Content-Disposition: form-data; name="image"; filename="user.jpg"
Content-Type: image/jpeg

< ./user.jpg
--boundary123--



###
GET http://localhost:3000/practica/user/getUser
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2U0MTIzMDViNmJlYWE3OTZhMDEzZWQiLCJyb2xlIjpbInVzZXIiXSwiaWF0IjoxNzQzMDcwNzUxLCJleHAiOjE3NDMwNzc5NTF9.wYIKyJx0q9qbDvWmhVGzfPGuBusRRPCysDW18mOajIw



###
DELETE http://localhost:3000/practica/user/deleteUser?soft=false
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2U0MTIzMDViNmJlYWE3OTZhMDEzZWQiLCJyb2xlIjpbInVzZXIiXSwiaWF0IjoxNzQzMDcwNzUxLCJleHAiOjE3NDMwNzc5NTF9.wYIKyJx0q9qbDvWmhVGzfPGuBusRRPCysDW18mOajIw



###
GET http://localhost:3000/practica/user/recuperarPassword/verificationCode
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2RjMjk5MTI2MTRlZWVjYjJkZWFmMTAiLCJyb2xlIjpbInVzZXIiXSwiaWF0IjoxNzQzMDc1NTMzLCJleHAiOjE3NDMwODI3MzN9.qlBSulG2Evf3jrvyPrVsxHhnfk5aImRA8Ec-tBh4z8c



###
POST http://localhost:3000/practica/user/recuperarPassword/verificationCode
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2RjMjk5MTI2MTRlZWVjYjJkZWFmMTAiLCJyb2xlIjpbInVzZXIiXSwiaWF0IjoxNzQzMDgyOTc4LCJleHAiOjE3NDMwOTAxNzh9.xrOw7qnexlPNFvs4K8wJ60MGjqeqsQz5yXvnZJ76FhM
Content-Type: application/json

{
    "email": "jopetis28@gmail.com",
    "code_verification": "0672b5"
}




###
POST http://localhost:3000/practica/user/recuperarPassword/changePassword
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2RjMjk5MTI2MTRlZWVjYjJkZWFmMTAiLCJyb2xlIjpbInVzZXIiXSwiaWF0IjoxNzQzMDg1NDQ1LCJleHAiOjE3NDMwOTI2NDV9.6OAXHnmBfhZyHSNHkFVERZp5CFIYHIgCgFRXc_y8o8Q
Content-Type: application/json

{
    "password": "12345678"
}




###
POST http://localhost:3000/practica/user/invitarGente
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2RjMjk5MTI2MTRlZWVjYjJkZWFmMTAiLCJyb2xlIjpbInVzZXIiXSwiaWF0IjoxNzQzMTUwMzQ4LCJleHAiOjE3NDMxNTc1NDh9.QC7XLCGIk-upDwZnfIE54lVOx01CIjirLq5uaknMSvs
Content-Type: application/json

{
    "partners": ["jopeetass@gmail.com", "email3@gmail.com", "jopetis28@gmail.com"]
}



#########################
# C  L  I  E  N  T  S
###
POST http://localhost:3000/practica/client
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2ODEzODUxYmQ3ZDZlYjZmNzNiNzQzZmMiLCJyb2xlIjpbInVzZXIiXSwiaWF0IjoxNzQ2MTc2NzMxLCJleHAiOjE3NDYxODM5MzF9.J9e2tt9vgDw0iWxW7vTgUdY366nYLLveXJqlu0RyCWE
Content-Type: application/json

{
    "name": "cliente2",
    "cif": "12345678A",
    "address": "Madrid"
}

###
PATCH http://localhost:3000/practica/client/12
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2ODEzNGZlMWEwNzZjMWU1M2ZkNGIxYTIiLCJyb2xlIjpbInVzZXIiXSwiaWF0IjoxNzQ2MDk2MTI5LCJleHAiOjE3NDYxMDMzMjl9.ipdgeR_wOzCCczBxfYJWzAUUYlLAzrF02W_0zAMSUQo
Content-Type: application/json

{
    "name": "clienteModificado",
    "probando": "probado"
}

###
GET http://localhost:3000/practica/client
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2ODEzODUxYmQ3ZDZlYjZmNzNiNzQzZmMiLCJyb2xlIjpbInVzZXIiXSwiaWF0IjoxNzQ2MTA5NzM5LCJleHAiOjE3NDYxMTY5Mzl9.IL4LzZ0ZN5p8sqFMw5GwKQpZpKWc30ZhI4EePrxItzQ

###
GET http://localhost:3000/practica/client/68138543d7d6eb6f73b74406
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2ODEzODUxYmQ3ZDZlYjZmNzNiNzQzZmMiLCJyb2xlIjpbInVzZXIiXSwiaWF0IjoxNzQ2MTA5NzM5LCJleHAiOjE3NDYxMTY5Mzl9.IL4LzZ0ZN5p8sqFMw5GwKQpZpKWc30ZhI4EePrxItzQ

###
DELETE http://localhost:3000/practica/client/deleteClient?soft=true
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2ODEzODUxYmQ3ZDZlYjZmNzNiNzQzZmMiLCJyb2xlIjpbInVzZXIiXSwiaWF0IjoxNzQ2MTc2NzMxLCJleHAiOjE3NDYxODM5MzF9.J9e2tt9vgDw0iWxW7vTgUdY366nYLLveXJqlu0RyCWE
Content-Type: application/json

{
    "cif": "12345678A"
}

###
POST http://localhost:3000/practica/client/restore/68148efa7ae09a0502a7a5e1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2ODEzODUxYmQ3ZDZlYjZmNzNiNzQzZmMiLCJyb2xlIjpbInVzZXIiXSwiaWF0IjoxNzQ2MTgzMzMwLCJleHAiOjE3NDYxOTA1MzB9.vMDwcXH1sivK5H6mcUEABbZe06jY6uVJ6IMmR4j1bss



###########################
# P  R  O  J  E  C  T  S
###
POST http://localhost:3000/practica/project
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2ODEzODUxYmQ3ZDZlYjZmNzNiNzQzZmMiLCJyb2xlIjpbInVzZXIiXSwiaWF0IjoxNzQ2MTk4MzI0LCJleHAiOjE3NDYyMDU1MjR9.h9eOudznF4pJrAP5QHPBeV2wv9ojwMqbTI6p2ACsrmY
Content-Type: application/json

{
    "clientId": "68148efa7ae09a0502a7a5e1",
    "projectCode": "123",
    "name": "prueba",
    "address": "Madrid"
}

###
PATCH http://localhost:3000/practica/project/6814a50d2d464a6be0aaf2aa
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2ODEzODUxYmQ3ZDZlYjZmNzNiNzQzZmMiLCJyb2xlIjpbInVzZXIiXSwiaWF0IjoxNzQ2MTk4MzI0LCJleHAiOjE3NDYyMDU1MjR9.h9eOudznF4pJrAP5QHPBeV2wv9ojwMqbTI6p2ACsrmY
Content-Type: application/json

{
    "name": "modificado"
}

###
GET http://localhost:3000/practica/project
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2ODEzODUxYmQ3ZDZlYjZmNzNiNzQzZmMiLCJyb2xlIjpbInVzZXIiXSwiaWF0IjoxNzQ2MTk4MzI0LCJleHAiOjE3NDYyMDU1MjR9.h9eOudznF4pJrAP5QHPBeV2wv9ojwMqbTI6p2ACsrmY

###
GET http://localhost:3000/practica/project/6814a50d2d464a6be0aaf2aa
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2ODEzODUxYmQ3ZDZlYjZmNzNiNzQzZmMiLCJyb2xlIjpbInVzZXIiXSwiaWF0IjoxNzQ2MTk4MzI0LCJleHAiOjE3NDYyMDU1MjR9.h9eOudznF4pJrAP5QHPBeV2wv9ojwMqbTI6p2ACsrmY

###
DELETE http://localhost:3000/practica/project/deleteProject?soft=true
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2ODEzODUxYmQ3ZDZlYjZmNzNiNzQzZmMiLCJyb2xlIjpbInVzZXIiXSwiaWF0IjoxNzQ2MTk4MzI0LCJleHAiOjE3NDYyMDU1MjR9.h9eOudznF4pJrAP5QHPBeV2wv9ojwMqbTI6p2ACsrmY
Content-Type: application/json

{
    "projectCode": "123"
}

###
POST http://localhost:3000/practica/project/restore/6814a50d2d464a6be0aaf2aa
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2ODEzODUxYmQ3ZDZlYjZmNzNiNzQzZmMiLCJyb2xlIjpbInVzZXIiXSwiaWF0IjoxNzQ2MTk4MzI0LCJleHAiOjE3NDYyMDU1MjR9.h9eOudznF4pJrAP5QHPBeV2wv9ojwMqbTI6p2ACsrmY



#######################################
# D  E  L  I  V  E  R  Y  N  O  T  E
###
POST http://localhost:3000/practica/deliverynote
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2ODEzODUxYmQ3ZDZlYjZmNzNiNzQzZmMiLCJyb2xlIjpbInVzZXIiXSwiaWF0IjoxNzQ2MzU1Mzg4LCJleHAiOjE3NDYzNjI1ODh9.Hr7j-NlWa2uqdExClLaHvPbRfL2iuJqnxV3fT9-nNWI
Content-Type: application/json

{
    "clientId": "68148efa7ae09a0502a7a5e1",
    "projectId": "6814a50d2d464a6be0aaf2aa",
    "name": "prueba",
    "format": "any",
    "hours": [
        {
            "description": "prueba",
            "quantity": 4
        }
    ],
    "material": [
        {
            "description": "prueba",
            "quantity": 4
        }
    ]
}

###
GET http://localhost:3000/practica/deliverynote
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2ODEzODUxYmQ3ZDZlYjZmNzNiNzQzZmMiLCJyb2xlIjpbInVzZXIiXSwiaWF0IjoxNzQ2MzU1Mzg4LCJleHAiOjE3NDYzNjI1ODh9.Hr7j-NlWa2uqdExClLaHvPbRfL2iuJqnxV3fT9-nNWI

###
GET http://localhost:3000/practica/deliverynote/68164c0a2f8ddab8500ca529
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2ODEzODUxYmQ3ZDZlYjZmNzNiNzQzZmMiLCJyb2xlIjpbInVzZXIiXSwiaWF0IjoxNzQ2MzcxOTQwLCJleHAiOjE3NDYzNzkxNDB9.LVORZy8481hRm3nWaHuXHZc42dzeXYPG0xiZw3CX2ng

###
GET http://localhost:3000/practica/deliverynote/pdf/68164c0a2f8ddab8500ca529
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2ODEzODUxYmQ3ZDZlYjZmNzNiNzQzZmMiLCJyb2xlIjpbInVzZXIiXSwiaWF0IjoxNzQ2MzcxOTQwLCJleHAiOjE3NDYzNzkxNDB9.LVORZy8481hRm3nWaHuXHZc42dzeXYPG0xiZw3CX2ng
