###
GET http://localhost:3000/practica/user

###
POST http://localhost:3000/practica/user/register
Content-Type: application/json

{
    "name": "ProbandoIntentos",
    "age": 20,
    "email": "jopeetass@gmail.com",
    "password": "12345678"
}

###
POST http://localhost:3000/practica/user/register/validation
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2RjMWUwZmUzYmJhMjU3MDQ1MjYyY2IiLCJyb2xlIjpbInVzZXIiXSwiaWF0IjoxNzQyNDc4ODYzLCJleHAiOjE3NDI0ODYwNjN9.BNJC_aQmTuVb4RApD47sXG_45WuqirSOHDSIDxfkieQ
Content-Type: application/json

{
    "code": "e4762e"
}


###
POST http://localhost:3000/practica/user/login
Content-Type: application/json

{
    "email": "jopetis28@gmail.com",
    "password": "123456789"
}