###
GET http://localhost:3000/practica/user

###
POST http://localhost:3000/practica/user/register
Content-Type: application/json

{
    "name": "ProbandoAutonomo",
    "age": 20,
    "email": "jopeetass@gmail.com",
    "password": "12345678"
}

###
POST http://localhost:3000/practica/user/register/validation
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2U0MTIzMDViNmJlYWE3OTZhMDEzZWQiLCJyb2xlIjpbInVzZXIiXSwiaWF0IjoxNzQzMDAwMTEyLCJleHAiOjE3NDMwMDczMTJ9.3YR3NdtTryIuYmls5e8G1wJnSHdtnXgtL67NCWJO7Ws
Content-Type: application/json

{
    "code": "893b21"
}


###
POST http://localhost:3000/practica/user/login
Content-Type: application/json

{
    "email": "jopetis28@gmail.com",
    "password": "12345678"
}


###
PUT http://localhost:3000/practica/user/personalData
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2U0MTIzMDViNmJlYWE3OTZhMDEzZWQiLCJyb2xlIjpbInVzZXIiXSwiaWF0IjoxNzQzMDAwNDYyLCJleHAiOjE3NDMwMDc2NjJ9.BCkGKXJTrxeE_ap_w8QHSqM9XrLawGYE6AVYTkqp9Hc
Content-Type: application/json

{
    "name2": "Diego22",
    "fullname": "Her",
    "nif": "12341234B"
}


###
PUT http://localhost:3000/practica/user/company
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2RjMjk5MTI2MTRlZWVjYjJkZWFmMTAiLCJyb2xlIjpbInVzZXIiXSwiaWF0IjoxNzQyOTk3MTc3LCJleHAiOjE3NDMwMDQzNzd9._c0BaPtkkdBVkVOf1xOz8ImJHZlciwHVdCro7gRiskw
Content-Type: application/json

{
    "name": "U-Tad",
    "cif": "12349078B",
    "address": "Rozas"
}


###
PATCH http://localhost:3000/practica/user/logo
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2U0MTIzMDViNmJlYWE3OTZhMDEzZWQiLCJyb2xlIjpbInVzZXIiXSwiaWF0IjoxNzQzMDcwNzUxLCJleHAiOjE3NDMwNzc5NTF9.wYIKyJx0q9qbDvWmhVGzfPGuBusRRPCysDW18mOajIw
Content-Type: multipart/form-data; boundary=boundary123

--boundary123
Content-Disposition: form-data; name="image"; filename="user.jpg"
Content-Type: image/jpeg

< ./user.jpg
--boundary123--



###
GET http://localhost:3000/practica/user/getUser
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2U0MTIzMDViNmJlYWE3OTZhMDEzZWQiLCJyb2xlIjpbInVzZXIiXSwiaWF0IjoxNzQzMDcwNzUxLCJleHAiOjE3NDMwNzc5NTF9.wYIKyJx0q9qbDvWmhVGzfPGuBusRRPCysDW18mOajIw



###
DELETE http://localhost:3000/practica/user/deleteUser?soft=false
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2U0MTIzMDViNmJlYWE3OTZhMDEzZWQiLCJyb2xlIjpbInVzZXIiXSwiaWF0IjoxNzQzMDcwNzUxLCJleHAiOjE3NDMwNzc5NTF9.wYIKyJx0q9qbDvWmhVGzfPGuBusRRPCysDW18mOajIw



###
GET http://localhost:3000/practica/user/recuperarPassword/verificationCode
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2RjMjk5MTI2MTRlZWVjYjJkZWFmMTAiLCJyb2xlIjpbInVzZXIiXSwiaWF0IjoxNzQzMDc1NTMzLCJleHAiOjE3NDMwODI3MzN9.qlBSulG2Evf3jrvyPrVsxHhnfk5aImRA8Ec-tBh4z8c